name: Release CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Verify tag format
        run: |
          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
            echo "Error: Tag ${{ github.ref_name }} does not match expected semver pattern 'vX.Y.Z(-prerelease)'"
            exit 1
          fi
          
      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          generate_release_notes: true

  build-and-upload:
    name: Build and Upload Artifacts
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-pc-windows-msvc, os: windows-latest, os_name: Windows, arch: x64, ext: .zip }
          - { target: x86_64-apple-darwin, os: macos-latest, os_name: macOS, arch: x64, ext: .tar.gz }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-latest, os_name: Linux, arch: x64, ext: .tar.gz }
          - { target: aarch64-apple-darwin, os: macos-latest, os_name: macOS, arch: arm64, ext: .tar.gz }
          - { target: aarch64-unknown-linux-musl, os: ubuntu-latest, os_name: Linux, arch: arm64, ext: .tar.gz }

    runs-on: ${{ matrix.os }}
    env:
      BINARY_NAME: sed-dl
      ARTIFACT_DIR: artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Show cache status
        run: 'echo "Cache hit: ${{ steps.cargo-cache.outputs.cache-hit }}"'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install cross-compilation tool (cross)
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: cargo install cross --git https://github.com/cross-rs/cross --branch main

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux' && contains(matrix.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Configure musl linker (Linux)
        if: runner.os == 'Linux' && contains(matrix.target, 'musl')
        run: |
          mkdir -p .cargo
          echo '[target.${{ matrix.target }}]' > .cargo/config.toml
          echo 'linker = "${{ matrix.target }}-gcc"' >> .cargo/config.toml
          echo 'rustflags = ["-C", "target-feature=+crt-static"]' >> .cargo/config.toml
      
      - name: Run tests
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]]; then
            cross test --release --target ${{ matrix.target }} --locked
          else
            cargo test --release --target ${{ matrix.target }} --locked
          fi
      
      - name: Build binary
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]]; then
            cross build --release --target ${{ matrix.target }} --locked
          else
            cargo build --release --target ${{ matrix.target }} --locked
          fi

      - name: Prepare binary for packaging
        id: prep_binary
        shell: bash
        run: |
          SOURCE_NAME=$( if [[ "${{ matrix.os }}" == "windows-latest" ]]; then echo "${{ env.BINARY_NAME }}.exe"; else echo "${{ env.BINARY_NAME }}"; fi )
          echo "source_name=$SOURCE_NAME" >> $GITHUB_OUTPUT
          SOURCE_PATH="target/${{ matrix.target }}/release/$SOURCE_NAME"
          echo "source_path=$SOURCE_PATH" >> $GITHUB_OUTPUT
          if [[ "${{ matrix.os }}" != "windows-latest" ]]; then
            strip "$SOURCE_PATH"
          fi

      - name: Package artifact and generate checksum
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ${{ env.ARTIFACT_DIR }}
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          SOURCE_NAME="${{ steps.prep_binary.outputs.source_name }}"
          SOURCE_PATH="${{ steps.prep_binary.outputs.source_path }}"
          DEST_ARCHIVE_NAME="${{ env.BINARY_NAME }}_${VERSION}_${{ matrix.os_name }}_${{ matrix.arch }}${{ matrix.ext }}"
          DEST_ARCHIVE_PATH="${{ env.ARTIFACT_DIR }}/$DEST_ARCHIVE_NAME"
          
          echo "Packaging $SOURCE_NAME for ${{ matrix.os_name }}..."
          if [[ "${{ matrix.ext }}" == ".zip" ]]; then
            zip -9 -j "$DEST_ARCHIVE_PATH" "$SOURCE_PATH"
          else
            tar -czf "$DEST_ARCHIVE_PATH" -C "$(dirname "$SOURCE_PATH")" "$SOURCE_NAME"
          fi
          
          echo "Generating checksum..."
          cd ${{ env.ARTIFACT_DIR }}
          sha256sum "$DEST_ARCHIVE_NAME" > "${DEST_ARCHIVE_NAME}.sha256"
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.ARTIFACT_DIR }}/*
          release_id: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    name: Publish Release
    needs: [create-release, build-and-upload]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish the Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          release_id: ${{ needs.create-release.outputs.release_id }}